#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

# Site settings
destination: _tds-local-dev

title: web assets
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site

username: Burt
password: Ernie

# Build settings
markdown: kramdown

permalink: pretty
relative_permalinks:

sass:
    style: expanded

# no longer watch for Sass file changes or compile them
exclude: [‘css’, ‘_scss’]

# don't erase the CSS directory in the _site output folder
keep_files: ['_tds-local-dev/css']
