# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: web assests
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# no longer watch for Sass file changes or compile them
exclude: [
  ‘css’,
  ‘_scss’,
  cws-pkg-builder-section.html,
  cws-pkg-builder-section1.html,
  cws-pkg-builder-wiki.html,
  cws-pkg-builder-page-wiki.html,
  cws-pkg-builder.html,
  2016-11-15-CWS-package-comparison-horizontal-wikimarkup.markdown,
  2016-11-16-CWS-package-comparison-vertical-wikimarkup.markdown,
  2017-1-25-Customer-Self-ID-wiki.markdown,
]

# don't erase the CSS directory in the _site output folder
keep_files: ['_tds-local-dev/css']
